// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PositiveNews.Core.Data;

#nullable disable

namespace PositiveNews.Core.Migrations
{
    [DbContext(typeof(PositiveNewsDbContext))]
    partial class PositiveNewsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("PositiveNews.Core.Entities.NewsStory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("PipelineRunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRunId");

                    b.ToTable("NewsStories");
                });

            modelBuilder.Entity("PositiveNews.Core.Entities.PipelineCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsPositive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PipelineRunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScoreReasoning")
                        .HasColumnType("TEXT");

                    b.Property<string>("Snippet")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Summarized")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRunId", "Url")
                        .IsUnique();

                    b.ToTable("PipelineCandidates");
                });

            modelBuilder.Entity("PositiveNews.Core.Entities.PipelineRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("RunDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicHint")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunDate")
                        .IsUnique();

                    b.ToTable("PipelineRuns");
                });

            modelBuilder.Entity("PositiveNews.Core.Entities.PipelineStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemLabel")
                        .HasColumnType("TEXT");

                    b.Property<int>("PipelineRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRunId");

                    b.ToTable("PipelineSteps");
                });

            modelBuilder.Entity("PositiveNews.Core.Entities.NewsStory", b =>
                {
                    b.HasOne("PositiveNews.Core.Entities.PipelineRun", "Run")
                        .WithMany("Stories")
                        .HasForeignKey("PipelineRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("PositiveNews.Core.Entities.PipelineCandidate", b =>
                {
                    b.HasOne("PositiveNews.Core.Entities.PipelineRun", "Run")
                        .WithMany("Candidates")
                        .HasForeignKey("PipelineRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("PositiveNews.Core.Entities.PipelineStep", b =>
                {
                    b.HasOne("PositiveNews.Core.Entities.PipelineRun", "Run")
                        .WithMany("Steps")
                        .HasForeignKey("PipelineRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("PositiveNews.Core.Entities.PipelineRun", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Steps");

                    b.Navigation("Stories");
                });
#pragma warning restore 612, 618
        }
    }
}
